### ISSUE TITLE
Error: Cannot find module '../../../package.json'

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/cli#15]
After `npm install -g @theintern/cli`

I try `intern run`

and get this error:

```
D:\dev\git_repos\harviewer2>intern run
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '../../../package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Paul\AppData\Roaming\npm\node_modules\@theintern\cli\bin\intern.js:23:13)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

If I uninstall globally, install locally (`npm install @theintern/cli --save-dev`), and try `npx intern help`

I get this:

```
Cannot find module '../../../package.json'
```

Same with:

```
D:\dev\git_repos\harviewer2>node node_modules\@theintern\cli\bin\intern.js help
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '../../../package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\dev\git_repos\harviewer2\node_modules\@theintern\cli\bin\intern.js:23:13)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

**Comment by gitgrimbo** [comment]
Fixed by installing the `@next` version:

`npm install @theintern/cli@next --save-dev`

Maybe update the docs to reflect the fact that `@next` is required until a 'real' 1.0.0 version is published.

**Comment by jason0x43** [comment]
Closing this since cli has been absorbed into the main intern repo, and that code doesn't exhibit this issue.
